export const StorageKeys = {
  PROFILE: 'profile',
  DAILY_WEIGHT_LOG: 'daily_weight_log',
  WORKOUT_HISTORY: 'workout_history',
  WORKOUT_PLANS: 'workout_plans',
  CACHE_METADATA: 'cache_metadata',
  APP_SETTINGS: 'app_settings',
  EXERCISE_FAVORITES: 'exercise_favorites',
  FRIEND_LIST: 'friend_list',
  EXERCISES_DATA: 'exercises_data',
  MUSCLE_GROUPS_DATA: 'muscle_groups_data',
  WORKOUT_CATEGORIES_DATA: 'workout_categories_data',
  DARK_MODE: 'dark_mode',
  FAVORITES: 'favorites',
  RECENT_EXERCISES: 'recent_exercises',
  EXERCISES: 'exercises',
  REDUCED_MOTION: 'reduced_motion',
  REDUCED_MOTION_USER_SET: 'reduced_motion_user_set',
  THEME_MODE: 'theme_mode',
  LAST_ONLINE: 'last_online',
  PENDING_OPERATIONS: 'pending_operations'
};